######################################################################
# Automatically generated by qmake (1.07a) Sat Jun 17 12:35:16 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += . ../../../linux/include ../../lib
CONFIG += debug

# Input
HEADERS += qv4l2.h general-tab.h
SOURCES += qv4l2.cpp general-tab.cpp ctrl-tab.cpp
LIBS += -lv4l2 -L../../lib
