#!/usr/bin/perl
use strict;

my %headers = (
	"video" => "videodev2.h",
);

my %structs;
my %ioc;
my $maxsize = 0;

sub print_union()
{
	printf "union v4l_parms {\n";
	printf "\tint		i;\n";
	printf "\tunsigned long	ulong;\n";
	printf "\tu_int32_t	u32;\n";
	printf "\tv4l2_std_id	id;\n";
	printf "\tenum v4l2_priority prio;\n";
	printf "\n\t/* V4L2 structs */\n";
	foreach my $s (keys %structs) {
		next if (!($s =~ m/struct/));
		$s =~ s/struct\s*//;

		my $ntabs = ($maxsize - length($s) - 7) / 8;
		my $tab = "";
		for (my $i = 0; $i < $ntabs; $i++) {
			$tab .= "\t";
		}


		printf "\tstruct %s%sp_%s;\n", $s, $tab, $s;
	}
	printf "};\n";
}

sub print_ioc()
{
	printf "#define ioc(cmd) { CMD32_##cmd, CMD64_##cmd, cmd, #cmd }\n";
	printf "\n/* All defined ioctls */\n";
	printf "static const struct {\n";
	printf "\tu_int32_t cmd32;\t/* The 32-bit ioctl value, should never change */\n";
	printf "\tu_int32_t cmd64;\t/* The 64-bit ioctl value, should never change */\n";
	printf "\tu_int32_t cmd;\n";
	printf "\tconst char *name;\n";
	printf "} ioctls[] = {\n";
	printf "\t/* V4L2 ioctls */\n";
	foreach my $ioctl (keys %ioc) {
		my $ntabs = ($maxsize - length($ioctl) - 6) / 8;
		my $tab = "";
		for (my $i = 0; $i < $ntabs; $i++) {
			$tab .= "\t";
		}

		printf "\tioc(%s),%s/* %s */\n", $ioctl, $tab, $ioc{$ioctl};
	}
	printf "};\n";
	printf "#define S_IOCTLS sizeof(ioctls)/sizeof(ioctls[0])\n";
}

printf "/* This file is auto-generated by make sync-with-kernel */\n";

foreach my $h (keys %headers) {
	printf "#include \"linux/%s\"\n\n", $headers{$h};

	open IN, "../../include/linux/" . $headers{$h};
	while (<IN>) {
		if (m/\#define\s+([A-Z][A-Z0-9_]+)\s+\_IO.+\(.*\,\s*([^\)]+)\)/) {
			$structs{$2} = 1;
			$ioc{$1} = $2;
			if ($maxsize < length($1)) {
				$maxsize = length($1);
			}
		}
		if (m/\#define\s+([A-Z][A-Z0-9_]+)\s+\_IO\(.*\)/) {
			$ioc{$1} = "void";
			if ($maxsize < length($1)) {
				$maxsize = length($1);
			}
		}
	}
	$maxsize = int(($maxsize + 7) / 8) * 8;
}

my $arg = shift;
if ($arg eq "--gen_ioctl_numbers") {
	printf "#include <stdio.h>\n";
	printf "int main(int argc, char *argv[]) {\n";
	printf "\tprintf(\"/* This file is auto-generated by make sync-with-kernel */\\n\\n\");\n";
	foreach my $ioctl (sort keys %ioc) {
		printf "\tprintf(\"#define CMD%%s_%s 0x%%x\\n\", argv[1], %s);\n", $ioctl, $ioctl;
	}
	printf "return 0;\n";
	printf "}\n";
} else {
	printf "#include \"ioctl_32.h\"\n";
	printf "#include \"ioctl_64.h\"\n\n";

	print_union();
	print_ioc();
}
