######################################################################
# Automatically generated by qmake (1.07a) Sat Jun 17 12:35:16 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += . ../../linux/include

# Input
HEADERS += qv4l2.h
SOURCES += qv4l2.cpp frequencies.c
