# Makefile for linuxtv.org v4l2-apps/util/xc3028-firmware

CPPFLAGS += -I../../include

binaries = rds-saa6588

.PHONY: all clean install qv4l2

all: $(binaries)

clean::
	rm -f $(binaries)

install:

include ../../Make.rules
